### ISSUE TITLE
Valg av spørrespråk for egenskapsspørriner (RQL, FIQL eller ODATA)

### ISSUE THREAD

**Issue by meastp** [kartverket/SFKB-API#2]
Fra rapport:

> Valg av spørrespråk: Resource Query Language (RQL), Feed Item Query Language (FIQL) eller ODATA
> Når vi skal legge på spørringer ved uttrekk, trenger vi en enkel måte å uttrykke spørringene på, som kan legges inn i en URI (query-parameter). RQL, FIQL, ODATA (Noark 5 benytter dette) og WFS 3.0 ( filtering on feature properties) er eksempler vi kan bruke.
> 
> Vi har funnet tre egnede spørrespråk for bruk i query-parametre, som gir uttrykk som er korte og enkle å lese. ODATA er en ISO-standard, men det er en veldig stor og omfattende standard som kan være tidkrevende for utviklere å sette seg inn i. FIQL og RQL er veldig enkle standarder som ikke er like utbredte. En fordel med FIQL og RQL er at de støtter in, slik at f.eks søk etter flere lokalider blir kort og konsist (med ODATA må man nøste med or). Se eksempel under.
> 
> Eksempel: Bygning med BYGGNR = 12345
> RQL: eq(Byging/bygningsnummer,12345)
> FIQL: Bygning/bygningsnummer=12345
> ODATA: Bygning/bygningsnummer eq 12345
> 
> Eksempel: Spørring etter ett bestemt objekt med gitt LOKALID
> RQL: eq(*/identifikasjon/lokalid,000a7b9b-7088-482f-a3cf-9761b97a54b6)
> FIQL: */identifikasjon/lokalid=000a7b9b-7088-482f-a3cf-9761b97a54b6
> ODATA: */identifikasjon/lokalid eq ‘000a7b9b-7088-482f-a3cf-9761b97a54b6’
> 
> Eksempel: Spørring etter flere objekter med gitt LOKALID
> RQL: in(*/identifikasjon/lokalid,(000a7b9b-7088-482f-a3cf-9761b97a54b6, 100a7b9b-7088-482f-a3cf-9761b97a54b7, 200a7b9b-7088-482f-a3cf-9761b97a54b8))
> FIQL: */identifikasjon/lokalid=in=(000a7b9b-7088-482f-a3cf-9761b97a54b6,100a7b9b-7088-482f-a3cf-9761b97a54b7,200a7b9b-7088-482f-a3cf-9761b97a54b8)
> ODATA: (*/identifikasjon/lokalid eq ‘000a7b9b-7088-482f-a3cf-9761b97a54b6’ or (*/identifikasjon/lokalid eq ‘100a7b9b-7088-482f-a3cf-9761b97a54b7’)) or (*/identifikasjon/lokalid eq ‘200a7b9b-7088-482f-a3cf-9761b97a54b8’)

Jeg foretrekker RQL eller FIQL pga. muligheten for **in**.

**Comment by larseggan** [comment]
helt greit for meg.

**Comment by meastp** [comment]
Fint. I spesifikasjonen har vi bruk RQL (uten foreløpig å nevne at det er RQL, bare hva synktaksen er - det er forsåvidt det samme som Microsoft gjør i sin Azure (Pipelines)). Beholder dette foreløpig hvis vi ikke hører noe annet.
