### ISSUE TITLE
Datasett bygning og spørring basert på lokalid gir feil tilbake

### ISSUE THREAD

**Issue by larsop** [kartverket/SFKB-API#31]
Fra java en java klient sender jeg følgende req

`
https://qmsrest.westeurope.cloudapp.azure.com:8080/v1/datasets/1eb5a249-c7c5-4328-9a7f-9c6d1ce6d526/features?locking=class Locking {
    type: user_lock
    id: 1
}&query=eq(*/identifikasjon/lokalid,000a7b9b-7088-482f-a3cf-9761b97a54b6)
`

og får tilbake 

`
INFO: Response Body: {"detail":"Klienten sendte en ugyldig forespørsel","errors":[{"reason":"Unsupported response type (application/vnd.kartverket.sosi+gml) in Content-Type header"}],"title":"Ugyldig forespørsel","type":"http://ngisopenapi.no/errors/request_error"}
`

**Comment by meastp** [comment]
Hei,
Kan du legge på headere som klienten sender fra seg?

**Comment by larsop** [comment]
Takk. 

Her er er header hvis det skulle være behov.
 
INFO: HTTP Headers: Server=[Microsoft-HTTPAPI/2.0],Content-Length=[246],Content-Type=[application/json],Date=[Thu, 07 Nov 2019 09:33:36 GMT]

**Comment by larsop** [comment]
Når endret header ble feil melding borte og jeg fikk tilbake noe data, men fikk da noen andre feil fordi det andre steder i den auto genererte koden fortsatt er en ref til soss+gml.

Jeg venter med å teste mere til koden er fikset på server siden.

**Comment by meastp** [comment]
@larsop Denne saken skal være løst - det var en feil med håndtering av Accept-headeren. Kan du teste og bekrefte dette?

**Comment by larsop** [comment]
Takk, da ser det det bedre ut
`
INFO: Response Body: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<gml:FeatureCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:app="http://skjema.geonorge.no/SOSI/produktspesifikasjon/FKB-Bygning/4.61" xmlns:gml="http://www.opengis.net/gml/3.2" gml:id="_263f8c9f-2715-4871-a1e9-1efccde49ba6" xsi:schemaLocation="http://skjema.geonorge.no/SOSI/produktspesifikasjon/FKB-Bygning/4.61 http://skjema.geonorge.no/SOSI/produktspesifikasjon/FKB-Bygning/4.61/FKB-Bygning461.xsd"></gml:FeatureCollection>
`
