### ISSUE TITLE
 https://qmsrest.westeurope.cloudapp.azure.com:8080/v1/datasets gir ingen dataset tilbake

### ISSUE THREAD

**Issue by larsop** [kartverket/SFKB-API#32]
URI: https://qmsrest.westeurope.cloudapp.azure.com:8080/v1/datasets

Accept=[application/json],Content-Type=[application/json],Authorization=[Basic bmliaW86bmliaW8=],User-Agent=[Java-SDK],Content-Length=[0]

får tilbake

INFO: Response Body: []

**Comment by meastp** [comment]
Det var en midlertidig driftsfeil mot databasen. Det er i orden nå.
