### ISSUE TITLE
Låsing: godt grensesnitt for query-parameter

### ISSUE THREAD

**Issue by meastp** [kartverket/SFKB-API#4]
I eksempelet jeg har laget er det litt kaos med hvordan query-parametrene på låsing er lagt opp. Dette skal jeg rette til noe enklere.

Parameteret skal brukes i både POST og GET for /datasets/{datasetid}, og må ta høyde for (selv om ikke alt kommer i første versjon):
- pessimistisk låsing med én lås for hver bruker per datasett
- optimistisk låsing
- pessimistisk låsing med låsenøkkel-id slik det er laget i dag, sånn at det er mulig med flere låser per bruker i ett arkiv (denne trengs kanskje ikke, må se om vi finner en elegant løsning hvor denne kan legges på dersom det blir nødvendig)

Jeg skal se på dette videre...

**Comment by meastp** [comment]
Jeg har lagt inn dette i spesifikasjonen nå for å ha et utgangspunkt.

**Comment by larseggan** [comment]
Ser greit ut.
