### ISSUE TITLE
Spesialtegn i description ødelegger for ts-klient

### ISSUE THREAD

**Issue by jarped** [kartverket/SFKB-API#40]
/* er i eksempelspørringen gjør at autogenerert kode for ts ikke fungerer.

https://github.com/kartverket/SFKB-API/blob/89cecfefaee587a37d99dd8211c23b074358dbfa/spec/openapi.yaml#L138

**Comment by meastp** [comment]
Jeg har flyttet dette ut til examples i #50 - hjelper det?

**Comment by jarped** [comment]
Kastet et raskt blikk på koden som genereres nå og det ser ut som det er i orden
