### ISSUE TITLE
Http-codes with XX-notation failes

### ISSUE THREAD

**Issue by jarped** [kartverket/SFKB-API#41]
Assumed to be a bug in nswag. This issue is just a reminder to create an issue in https://github.com/RicoSuter/NSwag

Should be allowed according to https://swagger.io/docs/specification/describing-responses/

https://github.com/kartverket/SFKB-API/blob/89cecfefaee587a37d99dd8211c23b074358dbfa/spec/openapi.yaml#L169

**Comment by meastp** [comment]
Dette skal være rettet i #50 - XX-notasjon er rettet til konkrete statuskoder.
