### ISSUE TITLE
Ulovlig boundingbox gir hele datasettet

### ISSUE THREAD

**Issue by jarped** [kartverket/SFKB-API#42]
Egentlig en bug i klientkoden men burde resultere i feilmelding fra server. Gir i dag hele datasettet:

https://qmsrest.westeurope.cloudapp.azure.com:8080/v1/datasets/1b3174b9-98bc-44ec-a8c0-a7c949d5a683/features?bbox=SFKB_API.BoundingBox

**Comment by meastp** [comment]
Denne er rettet lokalt.

**Comment by meastp** [comment]
Denne rettingen ligger i Azure-miljøet og kan testes.

**Comment by jarped** [comment]
Verifisert fikset
