### ISSUE TITLE
Dokumentasjon av GML/WFS-T med gml-id

### ISSUE THREAD

**Issue by meastp** [kartverket/SFKB-API#5]
For at "nye" utviklere skal kunne bruke dette grensesnittet trenger vi en god beskrivelse av hvordan dataene skal se ut.

Har vi kanskje et sted vi kan lenke til som inneholder beskrivelse av GML / WFS-T? Vi må også beskrive hvordan vi har gjort det med gml-id.

**Comment by larseggan** [comment]
Vi må få med dokumentasjon for lokalid og gmlid.
I tillegg rundt det med 3D: For Z NaN brukes verdien -99999.

**Comment by larseggan** [comment]
Når det gjelder delt geometri (benyttes i dag av QMS Geosynkronisering tilbyder) ligger det et notat på Dropbox jeg fikk fra Gunstein: Strategigruppe\SFKB API\delt_geometri_gmlid.pdf

**Comment by meastp** [comment]
Dette ligger nå i rapporten. Når rapporten er fullført, kan vi ta inn dette i wiki'en her.
